export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function AdminLayout({ children }: { children: React.ReactNode }) {
	return (
		<div>
			<h1>admin RootLayout</h1>
			{children}
		</div>
	)
}
